# Generated by Django 4.1.4 on 2023-01-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='زمان لازم'),
        ),
    ]
