# Generated by Django 4.1.4 on 2023-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_name_alter_food_photo_alter_food_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('B', 'صبحانه'), ('L', 'ناهار'), ('S', 'شام'), ('D', 'نوشیدنی')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
