# Generated by Django 4.1.4 on 2023-01-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام'), ('drinks', 'نوشیدنی')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
