# Generated by Django 4.1.4 on 2023-01-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='FoodComment',
        ),
    ]
