# Generated by Django 4.1.4 on 2023-01-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='blogs.tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=100, verbose_name='آدرس ایمیل')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان انتشار')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog', verbose_name='مقاله')),
            ],
        ),
    ]
